permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 12
comments: true
paginate_path: "/blog/page/:num/"

gems:
  - compass
  - jekyll-paginate

baseurl: null
domain_name: nandomoreira.me
google_analytics: UA-52446115-1

source:      source
destination: _site

itemtype: WebPage
cover: /assets/images/facebook.png

# site title, description, keywords
name: Fernando Moreira
title: Fernando Moreira • Desenvolvedor web e Front-end
description: "Desenvolvedor Front-end, Design Responsivo, HTML5, CSS3 e JavaScript"
keywords: "site, website, loja virtual, lojas virtuais, e-commerce, wordpress, frontend, front-end, html, html5, css, css3, js, javascript, jquery, seo, otimizacao, performance"
url: http://nandomoreira.me
repo: http://github.com/nandomoreirame/nandomoreirame.github.io
disqus_shortname: "fernandomoreira"
rss_path: source/
author:
  name      : Fernando Moreira
  image     : /assets/images/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  # facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  # instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."


# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
